scripts: zephyr_module: Fix optionality of "click-through" for blobs
When pykwalify was changed to jsonschema in commit e2bdfd3 the optionality
of 'click-through' was lost. Fix this by making sure there's always a value
in the dictionary, eliminating the following error when the key is missing:

if blob['click-through'] and not args.auto_accept:
   ~~~~^^^^^^^^^^^^^^^^^
KeyError: 'click-through'

Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>