Revert "drivers: sdhc: set SDHC_INIT_PRIORITY to KERNEL_INIT_PRIORITY_DEVICE"
This reverts commit 713cdff118395b2c3f55b211e4d4ba6c5a74d770.

Build error:

ERROR: /soc/mmc@ee140000 <rcar_mmc_init> is initialized before its
  dependency /regulator_1p8v <regulator_fixed_init>
ERROR: ... /regulator_3p3v <regulator_fixed_init>

Signed-off-by: Anas Nashif <anas.nashif@intel.com>