Revert "drivers: gpio_cc13xx_cc26xx: Update for latest sdk"
This reverts commit b582f2b02234e6edab3312451e5a31db991a50e4.

Breaks CI with the following compilation error in SPI.c:52:
error: 'SPI_MASTER' undeclared here (not in a function)

Failing tests (cc3220sf_launchxl/cc3220sf)
- sample.net.sockets.echo.offload.simplelink
- sample.net.sockets.http_get.offload.simplelink
- sample.net.wifi

Signed-off-by: Benjamin Cabé <benjamin@zephyrproject.org>