soc: silabs_exx32: define an empty pm_state_exit_post_ops
Some EFR32 build broke after 9ec45b3c47 with:

pm.c:152: undefined reference to `pm_state_exit_post_ops'

Add an extra empty function to make this one build again.

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>