modules: mbedtls: Fix build with address sanitizer and size opt
When building with the address sanitizer and size optimizations some of
the mbedtls assembler fails to build, with an error like:
error: ‘asm’ operand has impossible constraints or there are not enough
       registers

Avoid this issue by forcing speed optimizations for this problematic
file if any optimization is chosen.

A similar fix was originally introduced in the module:
https://github.com/zephyrproject-rtos/mbedtls/commit/4f1e8f5a78d
but it seems to have stoped working when the content of the file was
moved.

Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>