drivers: sensor: bmp581: ifdef static function
So it is only built when needed, and we avoid a compiler warning:
bmp581.c:59:19: error: unused function 'bmp581_pm_busy_check'

The issue was there since 5a3075999c8970d0fc362a952337f424657e8e0c
but only became apparent in CI when its test was added in
2cda8f34371878792cc680b0eda1b6a5c5ce8de4

Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>