doc: Fix html-live doc command
OUTPUT_DIR was not passed to the html-live target, causing a
Python exception:

```
TypeError: argument should be a str or an os.PathLike object
           where __fspath__ returns a str, not 'NoneType'
```

Signed-off-by: Aksel Skauge Mellbye <aksel.mellbye@silabs.com>