boards: em_starterkit: stop overriding GPIO_INIT_PRIORITY
This was introduced long time ago during a big priority refactoring,
with the current priority changes it should not be necesary anymore, the
current value is causing some build fail in the weekly test.

Fixes the following breakage:
```
$ west build -p -b em_starterkit_em11d -T
	tests/drivers/build_all/gpio/drivers.gpio.build
...
ERROR: /test/nct3807_alert_1 POST_KERNEL 52 51 <
	/test/gpio@deadbeef POST_KERNEL 70 47
ninja: build stopped: subcommand failed.
```

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>