tests: kernel: device: use zephyr/ prefix for generated syscall header
CONFIG_LEGACY_GENERATED_INCLUDE_PATH is deprecated and no longer
enabled by default, so the un-prefixed <syscalls/abstract_driver.h>
include path is not available anymore and the test fails to build:

  fatal error: syscalls/abstract_driver.h: No such file or directory

Use the zephyr/ prefixed path for the generated syscall header, as
done for all other syscall headers in the tree.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>