arch: arm: mmu: add missing includes
The samples/subsys/llext/shell_loader test fails when running as a
twister test on the stm32mp135f_dk/stm32mp135fxx platform, with the
following error:

zephyr/include/zephyr/arch/arm/mmu/arm_mmu.h:112:9:
error: unknown type name 'uintptr_t'

This commit adds the necessary includes to define the missing types.

Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@foss.st.com>