Revert "boards: silabs: siwx91x: Expose real layout of the flash"
This reverts commit 26420d0e38fcdf094fc734b832f0c36805943b37.

Some boards are failing with:

OverflowError: can't convert negative int to unsigned

Signed-off-by: Anas Nashif <anas.nashif@intel.com>